
;; -*- emacs-lisp -*-
;;
;;
;; name: color-theme-emacs-21
;; date: Sat Sep 25 2010 20:42:06 GMT+0200 (CET)
;;
;;
;; To use this theme save this code into a
;; file named color-theme-emacs-21.el and place it
;; in a directory in your load-path
;;
;;    (require 'color-theme-emacs-21)
;;    (color-theme-emacs-21)
;;


(require 'color-theme)

(defun color-theme-emacs-21-custom ()
  "Generated with http://color-theme-select.heroku.com/ on Sat Sep 25 2010 20:42:05 GMT+0200 (CET)
Color theme used by Emacs 21.1.
Added and adapted for XEmacs by Alex Schroeder.  Adaptation mostly
consisted of resolving :inherit attributes and adding missing faces.
This theme includes faces from the following Emacs libraries: add-log
calendar comint cus-edit cus-face custom diff-mode ediff-init re-builder
viper-init enriched em-ls em-prompt esh-test faces font-lock generic-x
gnus-art gnus-cite gnus message hilit-chg hi-lock info isearch log-view
paren pcvs-info antlr-mode cperl-mode ebrowse idlwave idlw-shell
make-mode sh-script vhdl-mode smerge-mode speedbar strokes artist
flyspell texinfo tex-mode tooltip vcursor wid-edit woman term man"
  (interactive)
  (color-theme-install
    '(color-theme-emacs-21
      (
       (background-color . "white")
       (background-mode . "light")
       (border-color . "black")
       (cursor-color . "black")
       (foreground-color . "black")
       (mouse-color . "black")
      )
      (
       (Man-overstrike-face . "bold")
       (Man-underline-face . "underline")
       (cperl-here-face . "font-lock-string-face")
       (cperl-invalid-face . "underline")
       (cperl-pod-face . "font-lock-comment-face")
       (cperl-pod-head-face . "font-lock-variable-name-face")
       (gnus-article-button-face . "bold")
       (gnus-article-mouse-face . "highlight")
       (gnus-cite-attribution-face . "gnus-cite-attribution-face")
       (gnus-mouse-face . "highlight")
       (gnus-signature-face . "gnus-signature-face")
       (gnus-summary-selected-face . "gnus-summary-selected-face")
       (help-highlight-face . "underline")
       (idlwave-class-arrow-face . "bold")
       (idlwave-shell-breakpoint-face . "idlwave-shell-bp-face")
       (idlwave-shell-expression-face . "secondary-selection")
       (idlwave-shell-stop-line-face . "highlight")
       (ispell-highlight-face . "highlight")
       (list-matching-lines-face . "bold")
       (view-highlight-face . "highlight")
       (viper-insert-state-cursor-color . "Green")
       (viper-replace-overlay-cursor-color . "Red")
       (widget-mouse-face . "highlight")
      )
      (default  ((t (:background "white" :foreground "black" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (Info-title-1-face  ((t (:bold t :weight bold :family "helv" :height 1.728))))
      (Info-title-2-face  ((t (:bold t :family "helv" :weight bold :height 1.44))))
      (Info-title-3-face  ((t (:bold t :weight bold :family "helv" :height 1.2))))
      (Info-title-4-face  ((t (:bold t :family "helv" :weight bold))))
      (antlr-font-lock-keyword-face  ((t (:bold t :foreground "black" :weight bold))))
      (antlr-font-lock-literal-face  ((t (:bold t :foreground "brown4" :weight bold))))
      (antlr-font-lock-ruledef-face  ((t (:bold t :foreground "blue" :weight bold))))
      (antlr-font-lock-ruleref-face  ((t (:foreground "blue4"))))
      (antlr-font-lock-tokendef-face  ((t (:bold t :foreground "blue" :weight bold))))
      (antlr-font-lock-tokenref-face  ((t (:foreground "orange4"))))
      (bold  ((t (:bold t :weight bold))))
      (bold-italic  ((t (:italic t :slant italic :weight bold))))
      (border  ((t (:background "black"))))
      (calendar-today-face  ((t (:underline t))))
      (change-log-acknowledgement-face  ((t (:foreground "Firebrick"))))
      (change-log-conditionals-face  ((t (:foreground "DarkGoldenrod"))))
      (change-log-date-face  ((t (:foreground "RosyBrown"))))
      (change-log-email-face  ((t (:foreground "DarkGoldenrod"))))
      (change-log-file-face  ((t (:foreground "Blue"))))
      (change-log-function-face  ((t (:foreground "DarkGoldenrod"))))
      (change-log-list-face  ((t (:foreground "Purple"))))
      (change-log-name-face  ((t (:foreground "CadetBlue"))))
      (comint-highlight-input  ((t (:bold t :weight bold))))
      (comint-highlight-prompt  ((t (:foreground "dark blue"))))
      (cperl-array-face  ((t (:bold t :background "lightyellow2" :foreground "Blue" :weight bold))))
      (cperl-hash-face  ((t (:italic t :background "lightyellow2" :foreground "Red" :slant italic :weight bold))))
      (cperl-nonoverridable-face  ((t (:foreground "chartreuse3"))))
      (cursor  ((t (:background "black"))))
      (custom-button-face  ((t (:background "lightgrey" :foreground "black" :box ( :line-width 2 :style released-button )))))
      (custom-button-pressed-face  ((t (:background "lightgrey" :foreground "black" :box ( :line-width 2 :style pressed-button )))))
      (custom-changed-face  ((t (:background "blue" :foreground "white"))))
      (custom-comment-face  ((t (:background "gray85"))))
      (custom-comment-tag-face  ((t (:foreground "blue4"))))
      (custom-face-tag-face  ((t (:bold t :family "helv" :weight bold :height 1.2))))
      (custom-group-tag-face  ((t (:bold t :foreground "blue" :weight bold :height 1.2))))
      (custom-group-tag-face-1  ((t (:bold t :family "helv" :foreground "red" :weight bold :height 1.2))))
      (custom-invalid-face  ((t (:background "red" :foreground "yellow"))))
      (custom-modified-face  ((t (:background "blue" :foreground "white"))))
      (custom-rogue-face  ((t (:background "black" :foreground "pink"))))
      (custom-saved-face  ((t (:underline t))))
      (custom-set-face  ((t (:background "white" :foreground "blue"))))
      (custom-state-face  ((t (:foreground "dark green"))))
      (custom-variable-button-face  ((t (:bold t :underline t :weight bold))))
      (custom-variable-tag-face  ((t (:bold t :family "helv" :foreground "blue" :weight bold :height 1.2))))
      (cvs-filename-face  ((t (:foreground "blue4"))))
      (cvs-handled-face  ((t (:foreground "pink"))))
      (cvs-header-face  ((t (:bold t :foreground "blue4" :weight bold))))
      (cvs-marked-face  ((t (:bold t :foreground "green3" :weight bold))))
      (cvs-msg-face  ((t (:italic t :slant italic))))
      (cvs-need-action-face  ((t (:foreground "orange"))))
      (cvs-unknown-face  ((t (:foreground "red"))))
      (diary-face  ((t (:foreground "red"))))
      (diff-context-face  ((t (:foreground "grey50"))))
      (diff-file-header-face  ((t (:bold t :background "grey70" :weight bold))))
      (diff-function-face  ((t (:foreground "grey50"))))
      (diff-header-face  ((t (:background "grey85"))))
      (diff-hunk-header-face  ((t (:background "grey85"))))
      (diff-index-face  ((t (:bold t :weight bold :background "grey70"))))
      (diff-nonexistent-face  ((t (:bold t :weight bold :background "grey70"))))
      (dired-face-boring  ((t (:foreground "RosyBrown"))))
      (dired-face-directory  ((t (:foreground "Blue"))))
      (dired-face-flagged  ((t (:foreground "Red" :weight bold))))
      (dired-face-marked  ((t (:foreground "Red" :weight bold))))
      (dired-face-symlink  ((t (:foreground "Purple"))))
      (ebrowse-file-name-face  ((t (:italic t :slant italic))))
      (ebrowse-member-attribute-face  ((t (:foreground "red"))))
      (ebrowse-member-class-face  ((t (:foreground "purple"))))
      (ebrowse-progress-face  ((t (:background "blue"))))
      (ebrowse-root-class-face  ((t (:bold t :foreground "blue" :weight bold))))
      (ebrowse-tree-mark-face  ((t (:foreground "red"))))
      (ediff-current-diff-face-A  ((t (:background "pale green" :foreground "firebrick"))))
      (ediff-current-diff-face-Ancestor  ((t (:background "VioletRed" :foreground "Black"))))
      (ediff-current-diff-face-B  ((t (:background "Yellow" :foreground "DarkOrchid"))))
      (ediff-current-diff-face-C  ((t (:background "Pink" :foreground "Navy"))))
      (ediff-even-diff-face-A  ((t (:background "light grey" :foreground "Black"))))
      (ediff-even-diff-face-Ancestor  ((t (:background "Grey" :foreground "White"))))
      (ediff-even-diff-face-B  ((t (:background "Grey" :foreground "White"))))
      (ediff-even-diff-face-C  ((t (:background "light grey" :foreground "Black"))))
      (ediff-fine-diff-face-A  ((t (:background "sky blue" :foreground "Navy"))))
      (ediff-fine-diff-face-Ancestor  ((t (:background "Green" :foreground "Black"))))
      (ediff-fine-diff-face-B  ((t (:background "cyan" :foreground "Black"))))
      (ediff-fine-diff-face-C  ((t (:background "Turquoise" :foreground "Black"))))
      (ediff-odd-diff-face-A  ((t (:background "Grey" :foreground "White"))))
      (ediff-odd-diff-face-Ancestor  ((t (:background "light grey" :foreground "Black"))))
      (ediff-odd-diff-face-B  ((t (:background "light grey" :foreground "Black"))))
      (ediff-odd-diff-face-C  ((t (:background "Grey" :foreground "White"))))
      (eshell-ls-archive-face  ((t (:bold t :foreground "Orchid" :weight bold))))
      (eshell-ls-backup-face  ((t (:foreground "OrangeRed"))))
      (eshell-ls-clutter-face  ((t (:bold t :foreground "OrangeRed" :weight bold))))
      (eshell-ls-directory-face  ((t (:bold t :foreground "Blue" :weight bold))))
      (eshell-ls-executable-face  ((t (:bold t :foreground "ForestGreen" :weight bold))))
      (eshell-ls-missing-face  ((t (:bold t :foreground "Red" :weight bold))))
      (eshell-ls-product-face  ((t (:foreground "OrangeRed"))))
      (eshell-ls-readonly-face  ((t (:foreground "Brown"))))
      (eshell-ls-special-face  ((t (:bold t :foreground "Magenta" :weight bold))))
      (eshell-ls-symlink-face  ((t (:bold t :foreground "Dark Cyan" :weight bold))))
      (eshell-ls-unreadable-face  ((t (:foreground "Grey30"))))
      (eshell-prompt-face  ((t (:bold t :foreground "Red" :weight bold))))
      (eshell-test-failed-face  ((t (:bold t :foreground "OrangeRed" :weight bold))))
      (eshell-test-ok-face  ((t (:bold t :foreground "Green" :weight bold))))
      (excerpt  ((t (:italic t :slant italic))))
      (fixed  ((t (:bold t :weight bold))))
      (fixed-pitch  ((t (:family "courier"))))
      (flyspell-duplicate-face  ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
      (flyspell-incorrect-face  ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
      (font-lock-builtin-face  ((t (:foreground "#00a"))))
      (font-lock-comment-face  ((t (:foreground "Firebrick"))))
      (font-lock-constant-face  ((t (:foreground "#070"))))
      (font-lock-doc-face  ((t (:foreground "RosyBrown"))))
      (font-lock-doc-string-face  ((t (:foreground "RosyBrown"))))
      (font-lock-function-name-face  ((t (:foreground "Blue"))))
      (font-lock-keyword-face  ((t (:foreground "Purple"))))
      (font-lock-preprocessor-face  ((t (:foreground "CadetBlue"))))
      (font-lock-reference-face  ((t (:foreground "Orchid"))))
      (font-lock-string-face  ((t (:foreground "RosyBrown"))))
      (font-lock-type-face  ((t (:foreground "ForestGreen"))))
      (font-lock-variable-name-face  ((t (:foreground "#000"))))
      (font-lock-warning-face  ((t (:bold t :foreground "Red" :weight bold))))
      (fringe  ((t (:background "grey95"))))
      (gnus-cite-attribution-face  ((t (:italic t :slant italic))))
      (gnus-cite-face-1  ((t (:foreground "MidnightBlue"))))
      (gnus-cite-face-10  ((t (:foreground "medium purple"))))
      (gnus-cite-face-11  ((t (:foreground "turquoise"))))
      (gnus-cite-face-2  ((t (:foreground "firebrick"))))
      (gnus-cite-face-3  ((t (:foreground "dark green"))))
      (gnus-cite-face-4  ((t (:foreground "OrangeRed"))))
      (gnus-cite-face-5  ((t (:foreground "dark khaki"))))
      (gnus-cite-face-6  ((t (:foreground "dark violet"))))
      (gnus-cite-face-7  ((t (:foreground "SteelBlue4"))))
      (gnus-cite-face-8  ((t (:foreground "magenta"))))
      (gnus-cite-face-9  ((t (:foreground "violet"))))
      (gnus-emphasis-bold  ((t (:bold t :weight bold))))
      (gnus-emphasis-bold-italic  ((t (:italic t :slant italic :weight bold))))
      (gnus-emphasis-highlight-words  ((t (:background "black" :foreground "yellow"))))
      (gnus-emphasis-italic  ((t (:italic t :slant italic))))
      (gnus-emphasis-underline  ((t (:underline t))))
      (gnus-emphasis-underline-bold  ((t (:bold t :underline t :weight bold))))
      (gnus-emphasis-underline-bold-italic  ((t (:italic t :underline t :slant italic :weight bold))))
      (gnus-emphasis-underline-italic  ((t (:italic t :underline t :slant italic))))
      (gnus-group-mail-1-empty-face  ((t (:foreground "DeepPink3"))))
      (gnus-group-mail-1-face  ((t (:bold t :foreground "DeepPink3" :weight bold))))
      (gnus-group-mail-2-empty-face  ((t (:foreground "HotPink3"))))
      (gnus-group-mail-2-face  ((t (:bold t :foreground "HotPink3" :weight bold))))
      (gnus-group-mail-3-empty-face  ((t (:foreground "magenta4"))))
      (gnus-group-mail-3-face  ((t (:bold t :foreground "magenta4" :weight bold))))
      (gnus-group-mail-low-empty-face  ((t (:foreground "DeepPink4"))))
      (gnus-group-mail-low-face  ((t (:bold t :foreground "DeepPink4" :weight bold))))
      (gnus-group-news-1-empty-face  ((t (:foreground "ForestGreen"))))
      (gnus-group-news-1-face  ((t (:bold t :foreground "ForestGreen" :weight bold))))
      (gnus-group-news-2-empty-face  ((t (:foreground "CadetBlue4"))))
      (gnus-group-news-2-face  ((t (:bold t :foreground "CadetBlue4" :weight bold))))
      (gnus-group-news-3-face  ((t (:bold t :weight bold))))
      (gnus-group-news-4-face  ((t (:bold t :weight bold))))
      (gnus-group-news-5-face  ((t (:bold t :weight bold))))
      (gnus-group-news-6-face  ((t (:bold t :weight bold))))
      (gnus-group-news-low-empty-face  ((t (:foreground "DarkGreen"))))
      (gnus-group-news-low-face  ((t (:bold t :foreground "DarkGreen" :weight bold))))
      (gnus-header-content-face  ((t (:italic t :foreground "indianred4" :slant italic))))
      (gnus-header-from-face  ((t (:foreground "red3"))))
      (gnus-header-name-face  ((t (:foreground "maroon"))))
      (gnus-header-newsgroups-face  ((t (:italic t :foreground "MidnightBlue" :slant italic))))
      (gnus-header-subject-face  ((t (:foreground "red4"))))
      (gnus-signature-face  ((t (:italic t :slant italic))))
      (gnus-splash-face  ((t (:foreground "Brown"))))
      (gnus-summary-cancelled-face  ((t (:background "black" :foreground "yellow"))))
      (gnus-summary-high-ancient-face  ((t (:bold t :foreground "RoyalBlue" :weight bold))))
      (gnus-summary-high-read-face  ((t (:bold t :foreground "DarkGreen" :weight bold))))
      (gnus-summary-high-ticked-face  ((t (:bold t :foreground "firebrick" :weight bold))))
      (gnus-summary-high-unread-face  ((t (:bold t :weight bold))))
      (gnus-summary-low-ancient-face  ((t (:italic t :foreground "RoyalBlue" :slant italic))))
      (gnus-summary-low-read-face  ((t (:italic t :foreground "DarkGreen" :slant italic))))
      (gnus-summary-low-ticked-face  ((t (:italic t :foreground "firebrick" :slant italic))))
      (gnus-summary-low-unread-face  ((t (:italic t :slant italic))))
      (gnus-summary-normal-ancient-face  ((t (:foreground "RoyalBlue"))))
      (gnus-summary-normal-read-face  ((t (:foreground "DarkGreen"))))
      (gnus-summary-normal-ticked-face  ((t (:foreground "firebrick"))))
      (gnus-summary-selected-face  ((t (:underline t))))
      (header-line  ((t (:box ( :line-width -1 :style released-button ) :background "grey90" :foreground "grey20"))))
      (hi-black-b  ((t (:bold t :weight bold))))
      (hi-black-hb  ((t (:bold t :family "helv" :weight bold :height 1.67))))
      (hi-blue  ((t (:background "light blue"))))
      (hi-blue-b  ((t (:bold t :foreground "blue" :weight bold))))
      (hi-green  ((t (:background "green"))))
      (hi-green-b  ((t (:bold t :foreground "green" :weight bold))))
      (hi-pink  ((t (:background "pink"))))
      (hi-red-b  ((t (:bold t :foreground "red" :weight bold))))
      (hi-yellow  ((t (:background "yellow"))))
      (highlight  ((t (:background "darkseagreen2"))))
      (highlight-changes-delete-face  ((t (:foreground "red" :underline t))))
      (highlight-changes-face  ((t (:foreground "red"))))
      (holiday-face  ((t (:background "pink"))))
      (idlwave-help-link-face  ((t (:foreground "Blue"))))
      (idlwave-shell-bp-face  ((t (:background "Pink" :foreground "Black"))))
      (info-header-node  ((t (:italic t :weight bold :slant italic :foreground "brown"))))
      (info-header-xref  ((t (:bold t :weight bold :foreground "magenta4"))))
      (info-menu-5  ((t (:foreground "red1"))))
      (info-menu-header  ((t (:bold t :family "helv" :weight bold))))
      (info-node  ((t (:italic t :foreground "brown" :slant italic :weight bold))))
      (info-xref  ((t (:bold t :foreground "magenta4" :weight bold))))
      (isearch  ((t (:background "green" :foreground "black"))))
      (isearch-lazy-highlight-face  ((t (:background "paleturquoise" :foreground "black"))))
      (italic  ((t (:italic t :slant italic))))
      (log-view-file-face  ((t (:bold t :background "grey70" :weight bold))))
      (log-view-message-face  ((t (:background "grey85"))))
      (makefile-space-face  ((t (:background "hotpink"))))
      (message-cited-text-face  ((t (:foreground "red"))))
      (message-header-cc-face  ((t (:foreground "MidnightBlue"))))
      (message-header-name-face  ((t (:foreground "cornflower blue"))))
      (message-header-newsgroups-face  ((t (:italic t :foreground "blue4" :slant italic :weight bold))))
      (message-header-other-face  ((t (:foreground "steel blue"))))
      (message-header-subject-face  ((t (:bold t :foreground "navy blue" :weight bold))))
      (message-header-to-face  ((t (:bold t :foreground "MidnightBlue" :weight bold))))
      (message-header-xheader-face  ((t (:foreground "blue"))))
      (message-mml-face  ((t (:foreground "ForestGreen"))))
      (message-separator-face  ((t (:foreground "brown"))))
      ;; (modeline  ((t (:background "grey75" :foreground "black" :box ( :line-width -1 :style released-button )))))
      ;; (modeline-buffer-id  ((t (:bold t :background "grey75" :foreground "black" :box ( :line-width -1 :style released-button ) :weight bold))))
      ;; (modeline-mousable  ((t (:background "grey75" :foreground "black" :box ( :line-width -1 :style released-button )))))
      ;; (modeline-mousable-minor-mode  ((t (:background "grey75" :foreground "black" :box ( :line-width -1 :style released-button )))))
      (mouse  ((t (:background "black"))))
      (primary-selection  ((t (:background "lightgoldenrod2"))))
      (reb-match-0  ((t (:background "lightblue"))))
      (reb-match-1  ((t (:background "aquamarine"))))
      (reb-match-2  ((t (:background "springgreen"))))
      (reb-match-3  ((t (:background "yellow"))))
      (region  ((t (:background "#8af"))))
      (scroll-bar  ((t (:background "grey75"))))
      (secondary-selection  ((t (:background "yellow"))))
      (sh-heredoc-face  ((t (:foreground "tan"))))
      (show-paren-match-face  ((t (:background "turquoise"))))
      (show-paren-mismatch-face  ((t (:background "purple" :foreground "white"))))
      (show-tabs-space-face  ((t (:foreground "yellow"))))
      (show-tabs-tab-face  ((t (:foreground "red"))))
      (smerge-base-face  ((t (:foreground "red"))))
      (smerge-markers-face  ((t (:background "grey85"))))
      (smerge-mine-face  ((t (:foreground "blue"))))
      (smerge-other-face  ((t (:foreground "darkgreen"))))
      (speedbar-button-face  ((t (:foreground "green4"))))
      (speedbar-directory-face  ((t (:foreground "blue4"))))
      (speedbar-file-face  ((t (:foreground "cyan4"))))
      (speedbar-highlight-face  ((t (:background "green"))))
      (speedbar-selected-face  ((t (:foreground "red" :underline t))))
      (speedbar-tag-face  ((t (:foreground "brown"))))
      (strokes-char-face  ((t (:background "lightgray"))))
      (term-black  ((t (:background "white" :foreground "black" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-blackbg  ((t (:background "black" :foreground "black" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-blue  ((t (:background "white" :foreground "blue" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-bluebg  ((t (:background "blue" :foreground "black" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-bold  ((t (:bold t :background "white" :foreground "black" :slant normal :weight bold :width normal :family "adobe-courier"))))
      (term-cyan  ((t (:background "white" :foreground "cyan" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-cyanbg  ((t (:background "cyan" :foreground "black" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-default  ((t (:background "white" :foreground "black" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-default-bg  ((t (:foreground "black" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-default-bg-inv  ((t (:foreground "black" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-default-fg  ((t (:background "white" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-default-fg-inv  ((t (:background "white" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-green  ((t (:background "white" :foreground "green" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-greenbg  ((t (:background "green" :foreground "black" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-invisible  ((t (:foreground "black" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-invisible-inv  ((t (:foreground "black" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-magenta  ((t (:background "white" :foreground "magenta" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-magentabg  ((t (:background "magenta" :foreground "black" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-red  ((t (:background "white" :foreground "red" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-redbg  ((t (:background "red" :foreground "black" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-underline  ((t (:background "white" :foreground "black" :underline t :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-white  ((t (:background "white" :foreground "white" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-whitebg  ((t (:background "white" :foreground "black" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-yellow  ((t (:background "white" :foreground "yellow" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (term-yellowbg  ((t (:background "yellow" :foreground "black" :slant normal :weight normal :width normal :family "adobe-courier"))))
      (tex-math-face  ((t (:foreground "RosyBrown"))))
      (texinfo-heading-face  ((t (:foreground "Blue"))))
      (tool-bar  ((t (:background "grey75" :foreground "black" :box ( :line-width 1 :style released-button )))))
      (tooltip  ((t (:background "lightyellow" :foreground "black"))))
      (trailing-whitespace  ((t (:background "red"))))
      (underline  ((t (:underline t))))
      (variable-pitch  ((t (:family "helv"))))
      (vcursor  ((t (:background "cyan" :foreground "blue" :underline t))))
      (vhdl-font-lock-attribute-face  ((t (:foreground "Orchid"))))
      (vhdl-font-lock-directive-face  ((t (:foreground "CadetBlue"))))
      (vhdl-font-lock-enumvalue-face  ((t (:foreground "Gold4"))))
      (vhdl-font-lock-function-face  ((t (:foreground "Orchid4"))))
      (vhdl-font-lock-prompt-face  ((t (:bold t :foreground "Red" :weight bold))))
      (vhdl-font-lock-reserved-words-face  ((t (:bold t :foreground "Orange" :weight bold))))
      (vhdl-font-lock-translate-off-face  ((t (:background "LightGray"))))
      (vhdl-speedbar-architecture-face  ((t (:foreground "Blue"))))
      (vhdl-speedbar-architecture-selected-face  ((t (:foreground "Blue" :underline t))))
      (vhdl-speedbar-configuration-face  ((t (:foreground "DarkGoldenrod"))))
      (vhdl-speedbar-configuration-selected-face  ((t (:foreground "DarkGoldenrod" :underline t))))
      (vhdl-speedbar-entity-face  ((t (:foreground "ForestGreen"))))
      (vhdl-speedbar-entity-selected-face  ((t (:foreground "ForestGreen" :underline t))))
      (vhdl-speedbar-instantiation-face  ((t (:foreground "Brown"))))
      (vhdl-speedbar-instantiation-selected-face  ((t (:foreground "Brown" :underline t))))
      (vhdl-speedbar-package-face  ((t (:foreground "Grey50"))))
      (vhdl-speedbar-package-selected-face  ((t (:foreground "Grey50" :underline t))))
      (viper-minibuffer-emacs-face  ((t (:background "darkseagreen2" :foreground "Black"))))
      (viper-minibuffer-insert-face  ((t (:background "pink" :foreground "Black"))))
      (viper-minibuffer-vi-face  ((t (:background "grey" :foreground "DarkGreen"))))
      (viper-replace-overlay-face  ((t (:background "darkseagreen2" :foreground "Black"))))
      (viper-search-face  ((t (:background "khaki" :foreground "Black"))))
      (widget-button-face  ((t (:bold t :weight bold))))
      (widget-button-pressed-face  ((t (:foreground "red"))))
      (widget-documentation-face  ((t (:foreground "dark green"))))
      (widget-field-face  ((t (:background "gray85"))))
      (widget-inactive-face  ((t (:foreground "dim gray"))))
      (widget-single-line-field-face  ((t (:background "gray85"))))
      (woman-addition-face  ((t (:foreground "orange"))))
      (woman-bold-face  ((t (:bold t :foreground "blue" :weight bold))))
      (woman-italic-face  ((t (:italic t :foreground "red" :underline t :slant italic))))
      (woman-unknown-face  ((t (:foreground "brown"))))
      (zmacs-region  ((t (:background "lightgoldenrod2"))))
      (minibuffer-prompt ((t (:foreground "dark blue"))))

     )
  )
)

(provide 'color-theme-emacs-21-custom)
